// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU5GyFhTSFLCDg622wP32FZCwkyxomEPo',
    appId: '1:409221304288:web:d1671a594c87a93d3ca585',
    messagingSenderId: '409221304288',
    projectId: 'stars-3cdc9',
    authDomain: 'stars-3cdc9.firebaseapp.com',
    storageBucket: 'stars-3cdc9.appspot.com',
    measurementId: 'G-D3RZKJV7X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKaVNiLYsZEEzTSASrxi4Ov4k_dsfRBkc',
    appId: '1:409221304288:android:9ae4f864e0f660903ca585',
    messagingSenderId: '409221304288',
    projectId: 'stars-3cdc9',
    storageBucket: 'stars-3cdc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxr3Kepdgw4s593etdc7Pz5P0aNZ36i5E',
    appId: '1:409221304288:ios:58c1a88faa606ebc3ca585',
    messagingSenderId: '409221304288',
    projectId: 'stars-3cdc9',
    storageBucket: 'stars-3cdc9.appspot.com',
    iosClientId: '409221304288-s931omvcle45sm41ogj29d1ikd1d0l5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.stars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxr3Kepdgw4s593etdc7Pz5P0aNZ36i5E',
    appId: '1:409221304288:ios:e77e75804a3ed3613ca585',
    messagingSenderId: '409221304288',
    projectId: 'stars-3cdc9',
    storageBucket: 'stars-3cdc9.appspot.com',
    iosBundleId: 'com.example.stars.RunnerTests',
  );
}
